### ISSUE TITLE
xFSK - extension module

### ISSUE THREAD

**Issue by HomeAutoUser** [HomeAutoUser/RFFHEM#10]
* For receiving and evaluating xFSK signals
* Develops Ralf - https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#

#############################################################################

Anpassung im weiteren Schritt - bisher offen:
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR67
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR69-R70
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR74
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR703-R709
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR880
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR890-R893
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1085-R1089
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1421-R1423
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1605-R1607
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1642

vermute "individuell"
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1092
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1136-R1140
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1144-R1168

Anpassung übernommen:
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR86
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR156-R157
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR191-R193
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR254
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR406-R412
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR958
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR2852-R2897
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR2948-R2951
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3326
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3423-R3427
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3448
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3460
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4556-R4670
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4872
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4933-R4936
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4994-R5004

Anpassung nicht notwendig:
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR120-R123

**Comment by HomeAutoUser** [comment]
@Ralf9 - Step 1

kannst du bitte mal hier

https://github.com/HomeAutoUser/RFFHEM/commit/456152d538887dc3bd3452214613b5f3655e37b5
https://github.com/HomeAutoUser/RFFHEM/commit/93dad38206612a07018824705707b0871b52a0b6

einen Blick drüber werfen ob das die Softwareseitige Anpassung für den ersten Schritt umfasst?
Ich habe erstmal die uC CMD weggelassen und mit dieser Anpassung sollte gewährleistet sein, das man auf jedenfall die Nachrichten dispatchen kann.

**Comment by Ralf9** [comment]
Ich finde es nicht so gut, daß Du für FSK andere ProtocollIds verwendest wie ich.
Dies gibt nur unnötige Verwirrung.

Bei Dir fehlt noch dies, damit kann ein LaCrosse Sensor recht komfortabel angelegt werden.
```
  } elsif( $cmd eq "LaCrossePairForSec" ) {
    return "Usage: set $name LaCrossePairForSec <seconds_active> [ignore_battery]" if(!$arg || $a[0] !~ m/^\d+$/ || ($a[1] && $a[1] ne "ignore_battery") );
    $hash->{LaCrossePair} = $a[1]?2:1;
    InternalTimer(gettimeofday()+$a[0], "SIGNALduino_RemoveLaCrossePair", $hash, 0);
```

Es fehlt auch noch die Anpassung für die "sub SIGNALduino_FingerprintFn($$)"
```
  if (substr($msg,0,2) eq "OK") {
    return;
  }
```
Das FingerprintFn() darf nur im physikalischen oder logischem Modul aktiv sein.
Wenn FingerprintFn in beiden aktiv ist, funktioniert der Dispatch nicht richtig.
Da FingerprintFn bei den LaCrosse Modulen verwendet wird, darf es im 00_Signalduino Modul nicht aktiv sein.

Ob das Verarbeiten und das Dispatchen von FSK raw Nachrichten funktioniert, kannst Du ja mit einem dummy sduino testen

**Comment by HomeAutoUser** [comment]
@Ralf9 danke für deinen Blick.
Ich habe es nun angepasst im Branch und werde die Variante testen mit dem normalen Dispatchen. Wenn dies reibungslos funktioniert ist dann der nächste Schritt, die Firmware was natürlich etwas schwieriger werden wird denke ich.

**Comment by HomeAutoUser** [comment]
@Ralf9, mit kommt noch eine Frage auf, wieso hast du das neue "Nachrichtenformat" MN benannt? Gibt es da einen Hintergrund? Wäre nicht MF passender weil es dort um sämtliche FSK "Varianten" geht?

**Comment by Ralf9** [comment]
> wieso hast du das neue "Nachrichtenformat" MN benannt

Ich habe es vom Cul übernommen, dort beginnen die raw Nachrichten mit N (Native)

**Comment by HomeAutoUser** [comment]
@Ralf9 wir setzen hier https://github.com/RFD-FHEM/RFFHEM/issues/814 fort.
