### ISSUE TITLE
New Command for Novy_840039 in 14_SD_UT.pm

### ISSUE THREAD

**Issue by Devirex** [HomeAutoUser/RFFHEM#11]
Description: 
`#     0111001000        "reset_clean_led"               - i.O.                                           hex_length 5    get sduino_dummy raw MU;;P0=-28556;;P1=402;;P2=-360;;P3=728;;P4=-724;;P5=-16068;;P6=-9560;;CP=1;;R=254;;D=01234123412123412341234123414141232341232323512341234123412341234141412323412323236;;e;;`

Command:
 "0111001000"  => "reset_clean_led",

Function:
Reset the green or red LED filter cleaning warning light.

**Comment by HomeAutoUser** [comment]
Hallo @Devirex,

welche Hardware nutzt du?
Gibt es eine genaue Bezeichnung von der Remote / Hardware welche das neue Kommando besitzt?

MfG

**Comment by Devirex** [comment]
Hallo, ich habe damals die Kommandos für die Novy Cloud 230 Dunstabzugshaube in Verbindung mit der Novy_840039 Fernbedienung geliefert. Jetzt habe ich ein weiteres Kommando zum reset der Filterreinigungs-LED entdeckt das hinzugefügt werden sollte damit man das per FHEM machen kann. Hintergrund: Alle 40 Kochstunden leuchtet eine LED dass man die Filter reinigen soll, hat man das gemacht kann man per doppelten Tastendruck die LED wieder ausschalten bzw. zurücksetzten. Der Code befindet sich in meinem Kommentar oben und muss im Plugin nur bei Novy_840039 ergänzt werden.
