### ISSUE TITLE
Testinformation

### ISSUE THREAD

**Issue by HomeAutoUser** [HomeAutoUser/RFFHEM#12]
Info to test :-)

Bitte testen @elektron-bbs 

**14_SD_AS.pm**
https://github.com/HomeAutoUser/RFFHEM/tree/master_SD_AT_pc
**14_SD_WS.pm**
https://github.com/HomeAutoUser/RFFHEM/tree/master_SD_WS_pc
**14_SD_WS07.pm**
https://github.com/HomeAutoUser/RFFHEM/tree/master_SD_WS07_pc

**Comment by elektron-bbs** [comment]
Tja, ich weiß nicht so recht, wie ich das deuten soll:
Ich hatte ca. 2 h deine Version der 14_SD_WS.pm installiert und damit ziemlich häufige Fehlermeldungen in dieser Art:

```
2020.12.21 18:14:04 3: sduinoIP: SD_WS_33 Parse msg W33#170684C0058 - ERROR check 15 != 6
2020.12.21 18:15:36 3: sduinoUSB0: SD_WS_33 Parse msg W33#31C19940034 - ERROR check 11 != 13
2020.12.21 18:16:26 3: sduinoIP: SD_WS_33 Parse msg W33#31C1D94002C - ERROR check 13 != 11
2020.12.21 18:16:44 3: sduinoIP: SD_WS_33 Parse msg W33#170504C009C - ERROR check 8 != 7
```

Dann habe ich wieder die ursprüngliche Version eingebunden und seitdem läuft der Empfang wieder problemlos seit ca. 1 h.
Das kann natürlich auch Zufall sein.

Im übrigen würde ich, wenn schon $VERSION definiert wird, diese auch gern angezeigt bekommen :-)

**Comment by HomeAutoUser** [comment]
>Im übrigen würde ich, wenn schon $VERSION definiert wird, diese auch gern angezeigt bekommen :-)

Solche Kleinigkeiten habe ich doch gern umgesetzt ;-)

>Tja, ich weiß nicht so recht, wie ich das deuten soll:
Ich hatte ca. 2 h deine Version der 14_SD_WS.pm installiert und damit ziemlich häufige Fehlermeldungen in dieser Art:
>
>2020.12.21 18:14:04 3: sduinoIP: SD_WS_33 Parse msg W33#170684C0058 - ERROR check 15 != 6
2020.12.21 18:15:36 3: sduinoUSB0: SD_WS_33 Parse msg W33#31C19940034 - ERROR check 11 != 13
2020.12.21 18:16:26 3: sduinoIP: SD_WS_33 Parse msg W33#31C1D94002C - ERROR check 13 != 11
2020.12.21 18:16:44 3: sduinoIP: SD_WS_33 Parse msg W33#170504C009C - ERROR check 8 != 7
>
>Dann habe ich wieder die ursprüngliche Version eingebunden und seitdem läuft der Empfang wieder problemlos seit ca. 1 h.
Das kann natürlich auch Zufall sein.

Dem Fall war ich auf die Spur gegangen und dies kommt, wenn man die Subroutine prototypes entfernt. Keine Ahnung wieso.
Die jetzige PC Überarbeitung würde ich als abgeschlossen betrachten weil wir da den Sprung von 990 auf knapp 540 Fehler machen. Die wichtigsten Stufen Warnings 5 & 4 sind beseitigt.

Diese Version 14_SD_WS.pm https://github.com/HomeAutoUser/RFFHEM/tree/master_SD_WS_pc würde ich einreichen wenn von Dir das ok kommt.

**Comment by elektron-bbs** [comment]
Hier hast du einmal "Gänsefüßchen" übersehen:
`  elsif  ($protocol eq '44' || $protocol eq "44x")
`

Den Zusammenhang verstehe ich trotz allem nicht. Warum funktioniert es bei der einen, bei der anderen nicht?
```
sub SD_WS_bin2dec($);
sub SD_WS_binaryToNumber;
```

Test läuft jetzt...

**Comment by HomeAutoUser** [comment]
>Diese Version 14_SD_WS.pm https://github.com/HomeAutoUser/RFFHEM/tree/master_SD_WS_pc würde ich einreichen wenn von Dir das ok kommt.

@elektron-bbs, konntest du bisher was feststellen? Ich bisher nicht.

>Den Zusammenhang verstehe ich trotz allem nicht. Warum funktioniert es bei der einen, bei der anderen nicht?

Ich habe mich dann nicht weiter damit befasst weil ich die Prototyps mit einmal entfernte bzw. rückgängig machte.
Man müsste für diese Spure einzeln mal die Prototypes ändern um vielleicht mit Hilfsausgaben dort erkennen zu können wieso das dannn falsch gedeutet / umgesetzt wird.

**Comment by elektron-bbs** [comment]
Ich hatte das noch soweit eingrenzen können, das offensichtlich "reverse" nicht oder zweimal ausgeführt wird:
Gleiche Nachricht, auf einem System wurde sie verarbeitet, auf dem anderen nicht:

```
BBS - SD_WS Original:
---------------------
sduino434_DMSG W33#260A7940034 
sduino434_MSGCNT 4371 
sduino434_Protocol_ID 33 
sduino434_RSSI -61 
sduino434_TIME 2020-12-22 11:30:31 

RaspberryPi3 - SD_WS MR:
------------------------
2020.12.22 11:30:30 3: sduinoIP: SD_WS_33 Parse msg W33#260A7940034 - ERROR check 11 != 13   - reverse geht nicht
```

Hier offensichtlich auch, gleiches System, aber verschiedene Empfänger:
```
2020.12.22 11:51:58 3: sduinoIP: SD_WS_33 Parse msg W33#260AF940004 - ERROR check 8 != 1   - reverse geht nicht
2020.12.22 11:51:58 3: sduinoACM: SD_WS_33 Parse msg W33#260AF940006 - ERROR check 8 != 1   - reverse geht nicht
```

Bisher läuft es bei mir unauffällig, mit folgenden Protokollen: 33, 51, 84 und 106.
Hast du die anderen schon getestet, oder verlässt du dich auf den Online-Test?
