### ISSUE TITLE
SD_UT - Umbau

### ISSUE THREAD

**Issue by HomeAutoUser** [HomeAutoUser/RFFHEM#4]
TEST (ISSUES auf meinem Clone für Umbau)
@elektron-bbs

**Comment by elektron-bbs** [comment]
Was willst du testen?
Ich habe meinen Plan, die ProtokollIdent zu verwenden erst mal verworfen, da sie ja leider nicht eindeutig ist.

**Comment by HomeAutoUser** [comment]
:-) ich wollte testen ob es geht selbst einen isu zu erstellen wo man "intern" kommunizieren kann ggf. Überlegungen austauschen kann.

>Ich habe meinen Plan, die ProtokollIdent zu verwenden erst mal verworfen, da sie ja leider nicht eindeutig ist.

genau richtig. Ich habe mir das heute mal durchdacht in ner ruhigen minute.

Name | Hex welche sich ändern
-- | --
SD_UT_81_HEX | 0-12
SD_UT_79_HEX | 0-12
SD_UT_293083_HEX | 4-8
SD_UT_293083_HEX | 0-8
SD_UT_293083_HEX | 0-8
SD_UT_293083_HEX | 1-4
SD_UT_8687_HEX | 0-12
SD_UT_8687_HEX | 0-12

ich komme zum entschluss, das man die protokoll id mit verankern müsste wie schon in der tabelle angedeutet.

**Comment by elektron-bbs** [comment]
Und was machen wir mit Protokollen, die unter zwei verschiedenen IDs demoduliert werden? Ich habe noch nicht nachgesehen, ob man gefahrlos eine ID weglassen könnte.

**Comment by HomeAutoUser** [comment]
Ich denke keine ID weglassen zu können wenn ich richtig schaute. Mir kommt nur der Weg am plausibelsten vor, das Modul einzukürzen auf die Variante fesge HexWerte wie remote oder Klingel und wo die Id an ner anderen Stelle ist zu nem anderen modul.

**Comment by HomeAutoUser** [comment]
Was hälst du von der Variante, beim DEF eines neuen gerätes, gleich alles Varianten als Def einzutragen und bei neuen Devices, den Hexwert prüfen in einer Schleife ob dieser scchon angelegt ist? Somit scchließen  wir auch aus, das die selben Hexwerte an Geräten genutzt werden.

v1_hex0-12
v2_hex_8-12
v3_hex_1-4

**Comment by elektron-bbs** [comment]
Zum einen weiß man nicht, wieviele Varianten es bei der Ident gibt. Was paasiert, wenn ein neues Gerät ausgerechnet eine ID benutzt, die schon irgendwo eingetragen ist?
Irgendei fällt mir noch keine gescheite Lösung ein.

**Comment by HomeAutoUser** [comment]
Erster Ansatz war ja, das Modul von der Klingel zu befreien. Ich denke, man kann das Modul nur erweitern mit Devices welche beim Empfang nur eine ID haben und nicht mehr auf einmal.

**Comment by elektron-bbs** [comment]
Die Klingel VTX-Bell hast du ja bereits entfernt. Da bleiben im Moment eigentlich nur noch Fernbedienungen und Türkontakte übrig.
Die Ident ist doch immer eindeutig pro Device. Das Problem ist nur, das wir nicht vorher wissen, welcher Teil der Nachricht die Ident darstellt, weil manche Nachrichten bei mehreren Protokollen passen. Deshalb erfolgt dann die Zuordnung mittels Attribut "model". Ich denke, das sollten wir so beibehalten.
