### ISSUE TITLE
dev-r34_new_model_SD_UT

### ISSUE THREAD

**Issue by elektron-bbs** [HomeAutoUser/RFFHEM#7]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer:
  - model name:
  - pictures of the device / the board (very helpful)

  
## Specifications 

  - Microcontroller:
  - Version (Firmware):
  

  - Versionmodul (FHEM Module):

**Comment by elektron-bbs** [comment]
Ich habe jetzt mal diese Version getestet und ein paar Veränderungen hinzugefügt.
clock jetzt für alle Fernbedienungen einstellbar
Attribut model kann von Novy_840029 in Novy_840039 und umgekehrt geändert werden.

Diese Ausgabe passt noch nicht so richtig:
![Zwischenablage-1](https://user-images.githubusercontent.com/26026988/73608536-a73e3580-45c4-11ea-9896-9159159cad51.png)

Mit Github Desktop sehe ich diesen Branch leider nicht, deshalb die Datei als Anhang:
[14_SD_UT.zip](https://github.com/HomeAutoUser/RFFHEM/files/4144192/14_SD_UT.zip)

**Comment by HomeAutoUser** [comment]
Ich vergleiche es mit der die ich hier habe. Scheinbar hat keiner gelesen das diese getestet werden sollte.

**Comment by HomeAutoUser** [comment]
@elektron-bbs 
imwesentlichen sind die Versionen gleich aber gern würde ich nochmal hinterfragen wieso du

1) 

`my $hex_lengh = $models{$oldmodel}{hex_lengh};` nutzen möchtest obwohl es mit 
`my $hex_lengh = length(InternalVal($name, "lastMSG", "0"));` direkter funktioniert. Somit sieht man, das man den Bezug auf das aktuelle Device hat.

2) 
`$modules{SD_UT}{defptr}{deletecache} = $name;	# delete old device` anstatt
`$modules{SD_UT}{defptr}{deletecache} = $name if ($hash->{DEF} eq "unknown");`
war das ein Fix welcher nicht aufgefallen war?

3)
`$attr{$devicename}{model}	= "$attrValue";				# set model` anstatt
`$attr{$devicename}{model}	= "$attrValue" if ($devicename ne "unknown_please_select_model");				# set model` was zu folge hätte, das Attribut wird immer gesetzt auch wenn es schon das model  `unknown_please_select_model` derzeit wäre.

4)
>Diese Ausgabe passt noch nicht so richtig:

Was passt dort noch nicht? Diese Meldung kommt, wenn ein Modell eingestellt ist und eine unbekkante Bitfolge für die Tasten kommt.

Außer Wertung:
x) ... bin ich am überlegen die direkten Hashzugriffe durch die Funktionen anfänglich zu ersten.
Bsp: `$attr{$devicename}{model} = " .... "`

**Comment by elektron-bbs** [comment]
1. bei Novy: hex_lengh => "3,5", - passt nie zu length der Nachricht
2. model Novy_840029 in Novy_840039 - löschen ging nur bei Model "unknown"
3. Einschränkung wie bei wie 2.
4. Da habe ich dann den Text wohl falsch gedeutet. Ich dachte es bedeutet "Fernbedienung benutzt einen existierenden Code" - bezogen auf DEF. Vieleicht dann besser "unknown message" oder so benutzen, oder wie vorher die Bitfolge ausgeben.

**Comment by HomeAutoUser** [comment]
>     1. bei Novy: hex_lengh => "3,5", - passt nie zu length der Nachricht

Die Länge ist doch 3 ODER 5. Also bitte nicht als 3,5 lesen.
Aus diesem Grund hatte ich gestern auch die Längenprüfung geändert.

>     2. model Novy_840029 in Novy_840039 - löschen ging nur bei Model "unknown"

ok, danke.

>     3. Einschränkung wie bei wie 2.

ok, danke.

>     4. Da habe ich dann den Text wohl falsch gedeutet. Ich dachte es bedeutet "Fernbedienung benutzt einen existierenden Code" - bezogen auf DEF. Vieleicht dann besser "unknown message" oder so benutzen, oder wie vorher die Bitfolge ausgeben.

Die unbekannte Bitfolge werde ich zusätzlich ausgeben. Vielleicht solle der Text besser so lauten
`Please check your model. The code is not supported. (11101010)`

**Comment by HomeAutoUser** [comment]
Ich hoffe ja, das https://github.com/RFD-FHEM/RFFHEM/pull/794 dieser nun durchläuft um den Stand erstmal wieder zu aktualisieren.

**Comment by elektron-bbs** [comment]
In der Liste steht aber bei Novy: hex_lengh => "3,5"
Der String ist demnach "3,5"
Hier wird geprüft:

`			return "ERROR! You want to choose the $oldmodel model to $attrValue.\nPlease check your selection.\nThe length of the messages must match!\n\nSuitable models would be: $allowed_models" if ($models{$attrValue}{hex_lengh} ne $hex_lengh && $oldmodel ne "unknown");	# variants one
`
Auszug davon:

`if ($models{$attrValue}{hex_lengh} ne $hex_lengh
`

Vorher war:

`my $hex_lengh = length(InternalVal($name, "lastMSG", "0"));`

Es wurde also verglichen "3,5" mit der Länge von "lastMSG" - das kann also niemals passen.

Jetzt vergleichen wir die Einträge aus der Liste und finden für Novy "3,5" eq "3,5" - können also das Attribut "model" ändern.

**Comment by elektron-bbs** [comment]
Ich habe es nochmal durchdacht und probiert: So ganz das Wahre ist das doch noch nicht.
Ich kann jetzt bei model unknown jedes model auswählen, egal welcher hex_length.

**Comment by HomeAutoUser** [comment]
Ich würde die ist-Länge der RAWMSG mit der Länge des einzustellenden Models prüfen. Diese muss gleich sein, dann ist umstellen möglich.

**Comment by elektron-bbs** [comment]
Ja, sehe ich auch so. Die Besonderheit ist aber bei Novy der Eintrag "3,5". Das kann man ja nicht mit "eq" verifizieren, man braucht "index" oder irgendein regex.

**Comment by HomeAutoUser** [comment]
Dann teste ggf mal die derzeitige Version bei mir im Branch.

Dort wird der Attributwert der Länge mit
`my $hex_lengh = length(InternalVal($name, "lastMSG", "0"));`
ermittelt und dann sollten
```
return "ERROR! You want to choose the $oldmodel model to $attrValue.\nPlease check your selection.\nThe length of RAWMSG must be the same!\n\nAllowed models are: $allowed_models" if ($models{$attrValue}{hex_lengh} !~ /$hex_lengh/ && $oldmodel ne "unknown");	# variants one
return "ERROR! You want to choose the unknown model to $attrValue.\nPlease check your selection.\nRAWMSG length is wrong!\n\nAllowed models are: $allowed_models" if (not ($models{$attrValue}{hex_lengh} =~ /($hex_lengh)/ ) && $oldmodel eq "unknown");				  # variants two/three
```
das abfangen.

Dort prüfen wir mit einem Regex.
