### ISSUE TITLE
Test function ccconf query

### ISSUE THREAD

**Issue by HomeAutoUser** [HomeAutoUser/RFFHEM#8]
@elektron-bbs
du kannst bitte mal die Funktion von dem https://github.com/HomeAutoUser/RFFHEM/tree/dev-r34_ccconf_query testen.

Bei einem Reset oder nach einem Neustart müsste automatisch ccconf ausgelesen werde.

**Comment by elektron-bbs** [comment]
Das funktioniert bei mir auch.

**Comment by HomeAutoUser** [comment]
Mal sehen wenn der BWidht fix durch ist, so würde ich das einreichen.

**Comment by elektron-bbs** [comment]
Das wiird sicher noch dauern, funktioniert ja noch nicht zuverlässig :-(

Ich muss etwas korrigieren: Bei meinem 2 System hat es nicht 100%ig funktioniert. Dort sind zwei SIGNALduinos dran. Bei einem erscheinen alle cc1101_.* bei dem zweiten nur die beiden:
cc1101_available 1 
cc1101_patable C3E = 00 C2 00 00 00 00 00 00 => 10_dBm 

Nach einem 2. Neustart gibt es bei beiden SIGNALduinos nur die beiden Einträge
Beim 3. Neustart wie 1.

**Comment by HomeAutoUser** [comment]
Das hat was mit dem abrufen zu tun. Wenn man nur einen Abruf bsp ccconf macht geht das zuverlässig. Sobald man Timer 2 mit patable nutzt, so kommt es zu solchen Differenzen. :(

**Comment by elektron-bbs** [comment]
Man müsste das sowieso aufsplitten:
Bei Neustart brauucht man ccconf und patable.
Bei set patable halt nur patable abrufen.
Bei set Bandbreite, Frequenz, rAmpl oder sens muss ccconf abgefragt werden.

**Comment by HomeAutoUser** [comment]
@elektron-bbs hier sollte die vollständige Aktualisierung sein wie du sie aufgezählt hast.
https://github.com/HomeAutoUser/RFFHEM/commit/4f00f0e0020e5190487a2c5e1f7c3b4e3a63eaf8
https://github.com/HomeAutoUser/RFFHEM/commit/2d2bf40d8ca637ca95ae6bbf36bebb14473ab944

Bitte mal testen mit
`update all https://raw.githubusercontent.com/HomeAutoUser/RFFHEM/dev-r34_config_query/controls_signalduino.txt`

**Comment by elektron-bbs** [comment]
Das funktioniert fast perfekt. Ich habe jetzt zwei Systeme mit dieser Aktualisierung jeweisl 5 mal neu gestartet.
Bei dem mit einem Radino und einem SIGNAL-ESP waren alle Werte immer da.
Bei dem anderen mit 2 SIGNALduino wurde von einem SIGNALduino 4 x alles aktualisiert und vom 2. SIGNALduino jeweils nur patable. Beim 5. Neustart war bei beiden SIGNALduinos nur patable zu sehen.

Wahrscheinlich reagieren die beiden SIGNALduinos gleichzeitig und FHEM kommt mit 2 Antworten zu gleicher Zeit nicht klar.
Bei der Kombination Radino und SIGNAL-ESP sind die Antwortzeiten ja sicher unterschiedlich, aufgrund verschiedener Anbindungen.

Evtl. müsste man mal probieren, die feste Verzögerung von 0.5 Sekunden mit einer Zufallszahl unterschiedlich zu gestalten, oder durchzählen und dann irgendeinen Wert addieren.

Die Reaktion beim Verstellen der Einstellungen scheint zu klappen. Kriegst du das auch noch hin, das bei "set raw e" (Werkseinstellung) die Werte aktualisiert werden? Dann wäre das perfekt.

**Comment by HomeAutoUser** [comment]
> Die Reaktion beim Verstellen der Einstellungen scheint zu klappen. Kriegst du das auch noch hin, das bei "set raw e" (Werkseinstellung) die Werte aktualisiert werden? Dann wäre das perfekt.

Das sollte sicherlich kein Problem darstellen.

Die unterschiedlichen Verzögerungen der Systeme hatte ich auch schon mitbekommen. Der Ansatz mit einer Zufallszahl klingt gut und muss ich mal verfolgen. Vielleicht ist es auch möglich, anhand des Hardwareattributes einen individuellen Zeitwert in einem Array zu hinterlegen. Ich versuche mal die Überlegung reifen.

**Comment by elektron-bbs** [comment]
Ich habe nochmal probiert:
Mit der Zufallszahl hat es auch nicht 100%ig funktioniert.
Ich habe dann jetzt die Konstante "SDUINO_CMD_TIMEOUT" verwendet. Dadurch kommen die Werte zwar erst 10 Sekunden verzögert, aber es scheint zu funktionieren.

```
InternalTimer(gettimeofday() + SDUINO_CMD_TIMEOUT, "SIGNALduino_Get_ConfigQuery", "SIGNALduino_Get_ConfigQuery:$name:ccpatable", 0);
InternalTimer(gettimeofday() + SDUINO_CMD_TIMEOUT + 1, "SIGNALduino_Get_ConfigQuery", "SIGNALduino_Get_ConfigQuery:$name:ccconf", 0);
```

Löscht dieses hier eigentlich alle Timer:
```
		if (exists($hash->{DevState}) && $hash->{DevState} eq 'waitInit') {
			RemoveInternalTimer($hash);
			$hash->{logMethod}->($hash, 3, "$name: CheckVersionResp, RemoveInternalTimer");
		}
```

Das würde dann erklären, das unsere Timer gelöscht werden, solange "Init" noch nicht abgeschlossen ist.

**Comment by HomeAutoUser** [comment]
@elektron-bbs hast du noch einmal getestet nach der Anpasung https://github.com/HomeAutoUser/RFFHEM/commit/faa45fb7d652bf8ac125b00fac5c7a34a7343e05 ?
Ich habe es hier laufen mit 3 Empfängern und dem ESP uns bisher klappte es ohne Probleme mit den aktuellen Timings

Ich setze einen Wert und es wird mir dann auch das Internal neu beschrieben nachdem ich natürlich manuell F5 für relaod drückte.
